from django.contrib import admin
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from apps.billing.views import CustomerViewSet, InvoiceViewSet

# Import all our ViewSets
from apps.inventory.views import CategoryViewSet, ProductViewSet
from apps.purchases.views import PurchaseOrderViewSet, VendorViewSet

# 1. Initialize the Router
router = DefaultRouter()

# 2. Register Inventory endpoints
router.register(r"categories", CategoryViewSet)
router.register(r"products", ProductViewSet)

# 3. Register Purchases endpoints
router.register(r"vendors", VendorViewSet)
router.register(r"purchase-orders", PurchaseOrderViewSet)

# 4. Register Billing endpoints
router.register(r"customers", CustomerViewSet)
router.register(r"invoices", InvoiceViewSet)

# 5. Wire them up
urlpatterns = [
    path("admin/", admin.site.urls),
    # This automatically includes all routes generated by the router
    # e.g., /api/products/ or /api/invoices/
    path("api/", include(router.urls)),
]
